
version: '3.4'

services:
  bandwithtester.workerservice:
    image: bandwithtester
    build:
      context: .
      dockerfile: BandwithTester/Dockerfile

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment: 
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./seq-data:/data

#    helloworld.workerservice:
#    image: helloworldworkerserivce
#    build:
#      context: .
#      dockerfile: HelloWorldWorkerService/Dockerfile

  # helloworld:
  #   image: helloworld
  #   build:
  #     context: .
  #     dockerfile: HelloWorld/Dockerfile

  # secondconsoleapp:
  #   image: secondconsoleapp
  #   build:
  #     context: .
  #     dockerfile: SecondConsoleApp/Dockerfile